/// Flutter icons Winas
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Winas
///      fonts:
///       - asset: fonts/Winas.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Winas {
  Winas._();

  static const _kFontFam = 'Winas';

  static const IconData word = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData gif = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData jpg = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData excel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData mov = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mp4 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData png = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ppt = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData wechat = const IconData(0xe808, fontFamily: _kFontFam);
}
